# Generated by Django 6.0.4 on 2026-04-21 20:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
        ('users', '0003_alter_studentprofile_experience_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Refusée'), ('withdrawn', 'Retirée')], default='pending', max_length=10, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.studentprofile', verbose_name='Étudiant'),
        ),
        migrations.AlterField(
            model_name='internshipoffer',
            name='description',
            field=models.TextField(verbose_name='Description détaillée'),
        ),
        migrations.AlterField(
            model_name='internshipoffer',
            name='duration_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Durée (mois)'),
        ),
        migrations.AlterField(
            model_name='internshipoffer',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Stage rémunéré ?'),
        ),
        migrations.AlterField(
            model_name='internshipoffer',
            name='required_skills',
            field=models.TextField(help_text='Texte libre analysé par TF-IDF. Ex: Python Django REST API Git Docker', verbose_name='Compétences requises'),
        ),
        migrations.AlterField(
            model_name='internshipoffer',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rémunération mensuelle (MAD)'),
        ),
        migrations.AlterField(
            model_name='internshipoffer',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'En pause'), ('archived', 'Archivée')], default='active', max_length=10, verbose_name='Statut'),
        ),
    ]
