# Generated by Django 6.0.4 on 2026-04-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_alter_application_status_alter_application_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipoffer',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contact'),
        ),
        migrations.AddField(
            model_name='internshipoffer',
            name='published_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de publication (externe)'),
        ),
        migrations.AddField(
            model_name='internshipoffer',
            name='source_platform',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Plateforme source (LinkedIn, Indeed, etc.)'),
        ),
        migrations.AddField(
            model_name='internshipoffer',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name="Lien d'origine pour postuler"),
        ),
    ]
