# Generated by Django 6.0.4 on 2026-04-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_internshipoffer_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipoffer',
            name='offer_type',
            field=models.CharField(choices=[('stage', 'Stage'), ('emploi', 'Emploi (CDI/CDD)'), ('freelance', 'Freelance')], default='stage', max_length=20, verbose_name="Type d'offre"),
        ),
    ]
