# Generated by Django 6.0.4 on 2026-04-21 20:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('users', '0003_alter_studentprofile_experience_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='computed_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Calculé le'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Score de similarité'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='users.studentprofile', verbose_name='Étudiant'),
        ),
    ]
