# Generated by Django 6.0.4 on 2026-04-27 22:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_alter_recommendation_computed_at_and_more'),
        ('users', '0004_studentprofile_expected_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='insights',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Details de recommandation'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='computed_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Calcule le'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Score de similarite'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='users.studentprofile', verbose_name='Etudiant'),
        ),
    ]
