# Generated by Django 6.0.4 on 2026-04-21 20:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'Profil Étudiant', 'verbose_name_plural': 'Profils Étudiants'},
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='experience_level',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Niveau d'expérience"),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='extracted_skills',
            field=models.TextField(blank=True, null=True, verbose_name="Compétences extraites par l'IA (JSON)"),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='projects',
            field=models.TextField(blank=True, null=True, verbose_name='Projets extraits (JSON)'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Secteur d'activité"),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Filière'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='graduation_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2035)], verbose_name='Année de diplôme'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='university',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Université / École'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Étudiant'), ('company', 'Entreprise'), ('admin', 'Administrateur')], default='student', max_length=10, verbose_name='Rôle'),
        ),
    ]
