# Generated by Django 6.0.4 on 2026-04-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_studentprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='experience_level',
            field=models.CharField(blank=True, default='Junior', max_length=50, null=True, verbose_name="Niveau d'expérience"),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='extracted_skills',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name="Compétences extraites par l'IA"),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='projects',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Projets extraits'),
        ),
    ]
