# Generated by Django 6.0.4 on 2026-04-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_studentprofile_experience_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='expected_salary',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Salaire vise (MAD)'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_locations',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Villes preferees'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_offer_types',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name="Types d'offres preferes"),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='remote_ok',
            field=models.BooleanField(default=True, verbose_name='Accepte le remote'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='target_job_titles',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Intitules vises'),
        ),
    ]
